In [3]:
# Dependencies and Setup
import pandas as pd
import quandl
import urllib.request, json

In [4]:
# Token key for accessing Quandl Data
quandl.ApiConfig.api_key = 'Tx8GhHmntW9csEbtjmH_'

In [5]:
Inventory_Measure_LA = quandl.get("ZILLOW/M436_IMP")
Inventory_Measure_LA['location'] = 'LA'
Inventory_Measure_LA['zillow_code'] = 'IMP'
Inventory_Measure_LA['description'] = 'Inventory Measure (Public)'
Inventory_Measure_LA.reset_index(inplace=True)

In [6]:
Inventory_Measure_LA

          Date    Value location zillow_code                 description
0   2010-01-31  44054.0       LA         IMP  Inventory Measure (Public)
1   2010-02-28  43092.0       LA         IMP  Inventory Measure (Public)
2   2010-03-31  42092.0       LA         IMP  Inventory Measure (Public)
3   2010-04-30  42049.0       LA         IMP  Inventory Measure (Public)
4   2010-05-31  41456.0       LA         IMP  Inventory Measure (Public)
5   2010-06-30  42774.0       LA         IMP  Inventory Measure (Public)
6   2010-07-31  43148.0       LA         IMP  Inventory Measure (Public)
7   2010-08-31  43522.0       LA         IMP  Inventory Measure (Public)
8   2010-09-30  44342.0       LA         IMP  Inventory Measure (Public)
9   2010-10-31  45722.0       LA         IMP  Inventory Measure (Public)
10  2010-11-30  45296.0       LA         IMP  Inventory Measure (Public)
11  2010-12-31  44991.0       LA         IMP  Inventory Measure (Public)
12  2011-01-31  42706.0       LA         IMP  Inventory Measure (Public)
13  2011-02-28  45120.0       LA         IMP  Inventory Measure (Public)
14  2011-03-31  48447.0       LA         IMP  Inventory Measure (Public)
15  2011-04-30  48422.0       LA         IMP  Inventory Measure (Public)
16  2011-05-31  48372.0       LA         IMP  Inventory Measure (Public)
17  2011-06-30  49043.0       LA         IMP  Inventory Measure (Public)
18  2011-07-31  50012.0       LA         IMP  Inventory Measure (Public)
19  2011-08-31  49123.0       LA         IMP  Inventory Measure (Public)
20  2011-09-30  46932.0       LA         IMP  Inventory Measure (Public)
21  2011-10-31  45054.0       LA         IMP  Inventory Measure (Public)
22  2011-11-30  44615.0       LA         IMP  Inventory Measure (Public)
23  2011-12-31  41940.0       LA         IMP  Inventory Measure (Public)
24  2012-01-31  39479.0       LA         IMP  Inventory Measure (Public)
25  2012-02-29  38707.0       LA         IMP  Inventory Measure (Public)
26  2012-03-31  36972.0       LA         IMP  Inventory Measure (Public)
27  2012-04-30  34010.0       LA         IMP  Inventory Measure (Public)
28  2012-05-31  32537.0       LA         IMP  Inventory Measure (Public)
29  2012-06-30  31380.0       LA         IMP  Inventory Measure (Public)
..         ...      ...      ...         ...                         ...
75  2016-04-30  18066.0       LA         IMP  Inventory Measure (Public)
76  2016-05-31  18856.0       LA         IMP  Inventory Measure (Public)
77  2016-06-30  20499.0       LA         IMP  Inventory Measure (Public)
78  2016-07-31  23662.0       LA         IMP  Inventory Measure (Public)
79  2016-08-31  23765.0       LA         IMP  Inventory Measure (Public)
80  2016-09-30  22016.0       LA         IMP  Inventory Measure (Public)
81  2016-10-31  20932.0       LA         IMP  Inventory Measure (Public)
82  2016-11-30  19603.0       LA         IMP  Inventory Measure (Public)
83  2016-12-31  16841.0       LA         IMP  Inventory Measure (Public)
84  2017-01-31  15242.0       LA         IMP  Inventory Measure (Public)
85  2017-02-28  15348.0       LA         IMP  Inventory Measure (Public)
86  2017-03-31  15509.0       LA         IMP  Inventory Measure (Public)
87  2017-04-30  15666.0       LA         IMP  Inventory Measure (Public)
88  2017-05-31  16528.0       LA         IMP  Inventory Measure (Public)
89  2017-06-30  17342.0       LA         IMP  Inventory Measure (Public)
90  2017-07-31  17254.0       LA         IMP  Inventory Measure (Public)
91  2017-08-31  17281.0       LA         IMP  Inventory Measure (Public)
92  2017-09-30  16904.0       LA         IMP  Inventory Measure (Public)
93  2017-10-31  16478.0       LA         IMP  Inventory Measure (Public)
94  2017-11-30  15210.0       LA         IMP  Inventory Measure (Public)
95  2017-12-31  12786.0       LA         IMP  Inventory Measure (Public)
96  2018-01-31  12188.0       LA         IMP  Inventory Measure (Public)
97  2018-02-28  13397.0       LA         IMP  Inventory Measure (Public)
98  2018-03-31  14170.0       LA         IMP  Inventory Measure (Public)
99  2018-04-30  15240.0       LA         IMP  Inventory Measure (Public)
100 2018-05-31  16840.0       LA         IMP  Inventory Measure (Public)
101 2018-06-30  18350.0       LA         IMP  Inventory Measure (Public)
102 2018-07-31  19558.0       LA         IMP  Inventory Measure (Public)
103 2018-08-31  20792.0       LA         IMP  Inventory Measure (Public)
104 2018-09-30  21553.0       LA         IMP  Inventory Measure (Public)

[105 rows x 5 columns]

# Indicators for 3 Metro areas: LA, SF, NY
* Los Angeles-Long Beach-Anaheim, CA
* San Francisco-Oakland-Hayward, CA
* New York-Newark-Jersey City, NY

#### IMP - Inventory Measure (Public)

In [3]:
# Zillow Home Value Index (Metro): Inventory Measure (Public)

LA_data = "https://www.quandl.com/api/v3/datasets/ZILLOW/M436_IMP.json?api_key=Tx8GhHmntW9csEbtjmH_"
SF_data = "https://www.quandl.com/api/v3/datasets/ZILLOW/M11_IMP.json?api_key=Tx8GhHmntW9csEbtjmH_"
NY_data = "https://www.quandl.com/api/v3/datasets/ZILLOW/M2_IMP.json?api_key=Tx8GhHmntW9csEbtjmH_"

data = urllib.request.urlopen(LA_data).read()
Inventory_Measure_LA = json.loads(data)

data = urllib.request.urlopen(SF_data).read()
Inventory_Measure_SF = json.loads(data)

data = urllib.request.urlopen(NY_data).read()
Inventory_Measure_NY = json.loads(data)

#### MRPAH - Median Rental Price - All Homes

In [4]:
# Zillow Home Value Index (Metro): Zillow Rental Index - All Homes

LA_data = "https://www.quandl.com/api/v3/datasets/ZILLOW/M436_ZRIAH.json?api_key=Tx8GhHmntW9csEbtjmH_"
SF_data = "https://www.quandl.com/api/v3/datasets/ZILLOW/M1047_ZRIAH.json?api_key=Tx8GhHmntW9csEbtjmH_"
NY_data = "https://www.quandl.com/api/v3/datasets/ZILLOW/M1105_ZRIAH.json?api_key=Tx8GhHmntW9csEbtjmH_"

data = urllib.request.urlopen(LA_data).read()
Rental_Index_LA = json.loads(data)

data = urllib.request.urlopen(SF_data).read()
Rental_Index_SF = json.loads(data)

data = urllib.request.urlopen(NY_data).read()
Rental_Index_NY = json.loads(data)

#### ZHVIAH - Home Value Index - All Homes

In [5]:
# Zillow Home Value Index (Metro): Zillow Home Value Index - All Homes

LA_data = "https://www.quandl.com/api/v3/datasets/ZILLOW/M436_ZHVIAH.json?api_key=Tx8GhHmntW9csEbtjmH_"
SF_data = "https://www.quandl.com/api/v3/datasets/ZILLOW/M1047_ZHVIAH.json?api_key=Tx8GhHmntW9csEbtjmH_"
NY_data = "https://www.quandl.com/api/v3/datasets/ZILLOW/M1105_ZHVIAH.json?api_key=Tx8GhHmntW9csEbtjmH_"

data = urllib.request.urlopen(LA_data).read()
home_value_LA = json.loads(data)

data = urllib.request.urlopen(SF_data).read()
home_value_SF = json.loads(data)

data = urllib.request.urlopen(NY_data).read()
home_value_NY = json.loads(data)

#### PHIVAH - Percent Of Homes Increasing In Values - All Homes

In [6]:
# Zillow Home Value Index (Metro): Percent Of Homes Increasing In Values - All Homes

LA_data = "https://www.quandl.com/api/v3/datasets/ZILLOW/M436_PHIVAH.json?api_key=Tx8GhHmntW9csEbtjmH_"
SF_data = "https://www.quandl.com/api/v3/datasets/ZILLOW/M1047_PHIVAH.json?api_key=Tx8GhHmntW9csEbtjmH_"
NY_data = "https://www.quandl.com/api/v3/datasets/ZILLOW/M1105_PHIVAH.json?api_key=Tx8GhHmntW9csEbtjmH_"

data = urllib.request.urlopen(LA_data).read()
homes_increasing_value_LA = json.loads(data)

data = urllib.request.urlopen(SF_data).read()
homes_increasing_value_SF = json.loads(data)

data = urllib.request.urlopen(NY_data).read()
homes_increasing_value_NY = json.loads(data)

#### PHDVAH - Percent Of Homes Decreasing In Values - All Homes

In [8]:
# Zillow Home Value Index (Metro): Percent Of Homes Decreasing In Values - All Homes

LA_data = "https://www.quandl.com/api/v3/datasets/ZILLOW/M436_PHDVAH.json?api_key=Tx8GhHmntW9csEbtjmH_"
SF_data = "https://www.quandl.com/api/v3/datasets/ZILLOW/M1047_PHDVAH.json?api_key=Tx8GhHmntW9csEbtjmH_"
NY_data = "https://www.quandl.com/api/v3/datasets/ZILLOW/M1105_PHDVAH.json?api_key=Tx8GhHmntW9csEbtjmH_"

data = urllib.request.urlopen(LA_data).read()
homes_decreasing_value_LA = json.loads(data)

data = urllib.request.urlopen(SF_data).read()
homes_decreasing_value_SF = json.loads(data)

data = urllib.request.urlopen(NY_data).read()
homes_decreasing_value_NY = json.loads(data)

In [9]:
homes_decreasing_value_NY

{'dataset': {'id': 44519533,
  'dataset_code': 'M1105_PHDVAH',
  'database_code': 'ZILLOW',
  'name': 'Zillow Home Value Index (Metro): Percent Of Homes Decreasing In Values - All Homes - New York-Newark-Jersey City, NY',
  'description': "The Zillow Home Value Index is Zillow's estimate of the median market value of percent of homes decreasing in values - all homes within the metro of New York-Newark-Jersey City, NY. This data is calculated by Zillow Real Estate Research (www.zillow.com/research) using their database of 110 million homes.",
  'refreshed_at': '2018-10-17T06:08:05.351Z',
  'newest_available_date': '2018-08-31',
  'oldest_available_date': '1997-02-28',
  'column_names': ['Date', 'Value'],
  'frequency': 'monthly',
  'type': 'Time Series',
  'premium': False,
  'limit': None,
  'transform': None,
  'column_index': None,
  'start_date': '1997-02-28',
  'end_date': '2018-08-31',
  'data': [['2018-08-31', 43.51],
   ['2018-07-31', 26.27],
   ['2018-06-30', 26.34],
   ['2018-05-31', 27.92],
   ['2018-04-30', 28.76],
   ['2018-03-31', 28.76],
   ['2018-02-28', 26.03],
   ['2018-01-31', 23.48],
   ['2017-12-31', 23.01],
   ['2017-11-30', 21.67],
   ['2017-10-31', 18.41],
   ['2017-09-30', 18.79],
   ['2017-08-31', 18.21],
   ['2017-07-31', 17.75],
   ['2017-06-30', 17.14],
   ['2017-05-31', 17.94],
   ['2017-04-30', 17.65],
   ['2017-03-31', 16.33],
   ['2017-02-28', 17.94],
   ['2017-01-31', 18.11],
   ['2016-12-31', 18.95],
   ['2016-11-30', 19.52],
   ['2016-10-31', 19.97],
   ['2016-09-30', 20.73],
   ['2016-08-31', 20.64],
   ['2016-07-31', 22.05],
   ['2016-06-30', 21.85],
   ['2016-05-31', 21.48],
   ['2016-04-30', 27.11],
   ['2016-03-31', 29.63],
   ['2016-02-29', 30.33],
   ['2016-01-31', 29.28],
   ['2015-12-31', 28.33],
   ['2015-11-30', 40.13],
   ['2015-10-31', 39.88],
   ['2015-09-30', 38.21],
   ['2015-08-31', 38.61],
   ['2015-07-31', 39.23],
   ['2015-06-30', 38.16],
   ['2015-05-31', 36.42],
   ['2015-04-30', 35.51],
   ['2015-03-31', 36.69],
   ['2015-02-28', 37.22],
   ['2015-01-31', 36.91],
   ['2014-12-31', 34.87],
   ['2014-11-30', 33.3],
   ['2014-10-31', 31.51],
   ['2014-09-30', 29.72],
   ['2014-08-31', 28.15],
   ['2014-07-31', 26.55],
   ['2014-06-30', 24.76],
   ['2014-05-31', 22.42],
   ['2014-04-30', 20.26],
   ['2014-03-31', 20.39],
   ['2014-02-28', 21.09],
   ['2014-01-31', 21.49],
   ['2013-12-31', 22.29],
   ['2013-11-30', 22.47],
   ['2013-10-31', 23.93],
   ['2013-09-30', 25.79],
   ['2013-08-31', 27.07],
   ['2013-07-31', 29.29],
   ['2013-06-30', 31.68],
   ['2013-05-31', 35.07],
   ['2013-04-30', 38.13],
   ['2013-03-31', 40.86],
   ['2013-02-28', 43.71],
   ['2013-01-31', 46.77],
   ['2012-12-31', 49.32],
   ['2012-11-30', 52.6],
   ['2012-10-31', 56.14],
   ['2012-09-30', 59.31],
   ['2012-08-31', 63.06],
   ['2012-07-31', 66.5],
   ['2012-06-30', 69.08],
   ['2012-05-31', 72.02],
   ['2012-04-30', 73.9],
   ['2012-03-31', 75.46],
   ['2012-02-29', 75.96],
   ['2012-01-31', 75.87],
   ['2011-12-31', 75.55],
   ['2011-11-30', 75.46],
   ['2011-10-31', 74.98],
   ['2011-09-30', 74.48],
   ['2011-08-31', 74.25],
   ['2011-07-31', 73.8],
   ['2011-06-30', 72.71],
   ['2011-05-31', 70.91],
   ['2011-04-30', 68.57],
   ['2011-03-31', 66.12],
   ['2011-02-28', 64.81],
   ['2011-01-31', 63.15],
   ['2010-12-31', 62.25],
   ['2010-11-30', 60.53],
   ['2010-10-31', 58.66],
   ['2010-09-30', 57.11],
   ['2010-08-31', 56.97],
   ['2010-07-31', 58.12],
   ['2010-06-30', 60.93],
   ['2010-05-31', 64.81],
   ['2010-04-30', 68.1],
   ['2010-03-31', 71.71],
   ['2010-02-28', 74.11],
   ['2010-01-31', 75.17],
   ['2009-12-31', 72.85],
   ['2009-11-30', 76.05],
   ['2009-10-31', 78.61],
   ['2009-09-30', 80.42],
   ['2009-08-31', 81.69],
   ['2009-07-31', 82.45],
   ['2009-06-30', 82.93],
   ['2009-05-31', 83.24],
   ['2009-04-30', 83.58],
   ['2009-03-31', 83.33],
   ['2009-02-28', 83.38],
   ['2009-01-31', 83.39],
   ['2008-12-31', 84.45],
   ['2008-11-30', 83.24],
   ['2008-10-31', 82.0],
   ['2008-09-30', 80.94],
   ['2008-08-31', 79.46],
   ['2008-07-31', 78.68],
   ['2008-06-30', 77.44],
   ['2008-05-31', 75.52],
   ['2008-04-30', 72.65],
   ['2008-03-31', 70.56],
   ['2008-02-29', 67.8],
   ['2008-01-31', 66.58],
   ['2007-12-31', 65.76],
   ['2007-11-30', 64.99],
   ['2007-10-31', 64.43],
   ['2007-09-30', 62.68],
   ['2007-08-31', 60.83],
   ['2007-07-31', 58.12],
   ['2007-06-30', 54.9],
   ['2007-05-31', 52.52],
   ['2007-04-30', 49.53],
   ['2007-03-31', 46.31],
   ['2007-02-28', 43.41],
   ['2007-01-31', 39.92],
   ['2006-12-31', 34.93],
   ['2006-11-30', 28.98],
   ['2006-10-31', 23.22],
   ['2006-09-30', 18.12],
   ['2006-08-31', 15.48],
   ['2006-07-31', 13.23],
   ['2006-06-30', 11.5],
   ['2006-05-31', 9.83],
   ['2006-04-30', 8.83],
   ['2006-03-31', 7.75],
   ['2006-02-28', 6.91],
   ['2006-01-31', 6.6],
   ['2005-12-31', 6.35],
   ['2005-11-30', 6.17],
   ['2005-10-31', 6.28],
   ['2005-09-30', 3.35],
   ['2005-08-31', 2.98],
   ['2005-07-31', 3.44],
   ['2005-06-30', 3.44],
   ['2005-05-31', 3.71],
   ['2005-04-30', 3.42],
   ['2005-03-31', 4.04],
   ['2005-02-28', 3.73],
   ['2005-01-31', 3.78],
   ['2004-12-31', 5.04],
   ['2004-11-30', 4.56],
   ['2004-10-31', 5.31],
   ['2004-09-30', 5.09],
   ['2004-08-31', 8.03],
   ['2004-07-31', 5.03],
   ['2004-06-30', 5.86],
   ['2004-05-31', 6.28],
   ['2004-04-30', 8.14],
   ['2004-03-31', 11.31],
   ['2004-02-29', 12.75],
   ['2004-01-31', 12.82],
   ['2003-12-31', 11.87],
   ['2003-11-30', 10.96],
   ['2003-10-31', 7.92],
   ['2003-09-30', 6.96],
   ['2003-08-31', 9.06],
   ['2003-07-31', 12.16],
   ['2003-06-30', 11.52],
   ['2003-05-31', 10.94],
   ['2003-04-30', 6.08],
   ['2003-03-31', 5.44],
   ['2003-02-28', 4.47],
   ['2003-01-31', 4.53],
   ['2002-12-31', 4.97],
   ['2002-11-30', 6.51],
   ['2002-10-31', 8.07],
   ['2002-09-30', 10.92],
   ['2002-08-31', 4.06],
   ['2002-07-31', 16.55],
   ['2002-06-30', 16.99],
   ['2002-05-31', 18.31],
   ['2002-04-30', 19.21],
   ['2002-03-31', 19.24],
   ['2002-02-28', 20.74],
   ['2002-01-31', 19.61],
   ['2001-12-31', 16.73],
   ['2001-11-30', 17.23],
   ['2001-10-31', 16.05],
   ['2001-09-30', 16.93],
   ['2001-08-31', 17.29],
   ['2001-07-31', 17.16],
   ['2001-06-30', 17.25],
   ['2001-05-31', 15.76],
   ['2001-04-30', 15.1],
   ['2001-03-31', 14.68],
   ['2001-02-28', 13.83],
   ['2001-01-31', 15.33],
   ['2000-12-31', 14.73],
   ['2000-11-30', 15.52],
   ['2000-10-31', 16.07],
   ['2000-09-30', 17.72],
   ['2000-08-31', 15.98],
   ['2000-07-31', 16.36],
   ['2000-06-30', 16.98],
   ['2000-05-31', 17.29],
   ['2000-04-30', 17.8],
   ['2000-03-31', 17.35],
   ['2000-02-29', 18.46],
   ['2000-01-31', 18.29],
   ['1999-12-31', 17.84],
   ['1999-11-30', 18.61],
   ['1999-10-31', 19.36],
   ['1999-09-30', 19.25],
   ['1999-08-31', 19.55],
   ['1999-07-31', 20.82],
   ['1999-06-30', 22.95],
   ['1999-05-31', 21.66],
   ['1999-04-30', 22.85],
   ['1999-03-31', 22.32],
   ['1999-02-28', 23.28],
   ['1999-01-31', 23.68],
   ['1998-12-31', 26.99],
   ['1998-11-30', 27.54],
   ['1998-10-31', 25.73],
   ['1998-09-30', 25.43],
   ['1998-08-31', 26.87],
   ['1998-07-31', 27.56],
   ['1998-06-30', 34.23],
   ['1998-05-31', 29.8],
   ['1998-04-30', 33.27],
   ['1998-03-31', 34.08],
   ['1998-02-28', 31.35],
   ['1998-01-31', 33.63],
   ['1997-12-31', 30.94],
   ['1997-11-30', 30.2],
   ['1997-10-31', 32.02],
   ['1997-09-30', 31.35],
   ['1997-08-31', 33.13],
   ['1997-07-31', 31.52],
   ['1997-06-30', 33.98],
   ['1997-05-31', 38.25],
   ['1997-04-30', 33.53],
   ['1997-03-31', 35.81],
   ['1997-02-28', 39.91]],
  'collapse': None,
  'order': None,
  'database_id': 15274}}